### ISSUE TITLE
pegjs ENOENT

### ISSUE THREAD

**Issue by albanm** [auth0/node-odata-parser#34]
Hello,

When installing node-odata-parser pegjs is used in preinstall script but fails with a ENOENT error.  Maybe because it is defined as a dev dep ? Anyway builds are broken.

Is it really necessary to have it both at prepublish and preinstall steps ?

**Comment by jfromaniello** [comment]
It is not, thanks for the heads up. I will fix asap

**Comment by jfromaniello** [comment]
Fixed,

**Comment by albanm** [comment]
Thanks !
